apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: user-service
              tier: backend
        spec:
            containers:
            - name: user-service
              image: sleepingtalent/user-service:1.0.1-RC
              env:
              - name: CONFIG_URL
                value: http://ae72c3afb915511e795a406fc096cf91-818673775.us-west-2.elb.amazonaws.com:1111/config-api/
              ports:
              - containerPort: 2222

---

kind: Service
metadata:
    name: user-service-gateway
    labels:
        app: user-service
        tier: backend
spec:
    type: LoadBalancer
    ports:
    - port: 2222
    selector:
        app: user-service
        tier: backend

