apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 1
    template:
        metadata:
            labels:
              app: user-service
              tier: backend
        spec:
            containers:
            - name: user-service
              image: sleepingtalent/user-service:1.0.1
              env:
              - name: CONFIG_URL
                value: http://10.52.180.42:1111/config-api/
              ports:
              - containerPort: 2222

